// AUTO-GENERATED from Seed Recipes.pdf
// Place this file next to seed.ts (same folder) and import { SEED_RECIPES } from "./seedRecipes";
export type SeedRecipe = {
  username: string;               // must match profiles.username
  title: string;
  caption: string | null;
  description: string;
  tags: string[];
  details: {
    servings: number | null;
    prep_time: string | null;     // e.g. "15m"
    cook_time: string | null;     // e.g. "35m"
    difficulty: "Easy" | "Medium" | "Hard" | string | null;
  };
  ingredients: string[];          // raw lines from PDF (we parse in seed.ts)
  steps: { position: number; body: string; timer_seconds?: number | null }[];
  image_url?: string | null;      // optional; seed.ts can fill if null
};

export const SEED_RECIPES: SeedRecipe[] = [
  {
    username: "mayavance",
    title: "Sunday Prep Harissa Chickpeas & Quinoa",
    caption: "Set your future self up for success ! Bold, spicy, and perfectly prepped .",
    description: "A high-flavor vegetarian meal prep staple. The harissa provides a deep, smoky heat that permeates the cauliflower and chickpeas during roasting .",
    tags: ["Vegetarian", "Healthy", "Spicy", "Quick"],
    details: {"servings": 4, "prep_time": "15 min", "cook_time": "35 min", "difficulty": "Easy"},
    ingredients: ["2 cans Chickpeas", "2 heads Cauliflower", "4 tbsp Harissa paste", "3 tbsp Olive oil", "1 tsp Cumin", "1 cup Quinoa", "1 Lemon", "1 bunch Kale"],
    steps: [{"position": 1, "body": "Preheat your oven to 400\u00b0F (200\u00b0C). Line two large rimmed baking sheets with parchment paper to prevent sticking."}, {"position": 2, "body": "Drain and rinse the chickpeas in a colander. Transfer them to a clean kitchen towel and pat them until they are bone-dry; moisture is the enemy of crunch."}, {"position": 3, "body": "Break the cauliflower into small, uniform florets (about 1-inch wide)."}, {"position": 4, "body": "In a very large mixing bowl, whisk together the harissa paste, olive oil, and cumin until smooth."}, {"position": 5, "body": "Add the dry chickpeas and cauliflower florets to the bowl. Use your hands or a spatula to toss them for at least 2 minutes, ensuring every crevice of the cauliflower is stained red."}, {"position": 6, "body": "Spread the mixture onto the baking sheets. Ensure they are in a single layer with space between items; if you crowd the pan, they will steam instead of roast."}, {"position": 7, "body": "Slide into the oven and roast for 30\u201335 minutes. At the 15-minute mark, use a spatula to flip and rotate the pieces."}, {"position": 8, "body": "While roasting, boil 2 cups of water and add 1 cup of rinsed quinoa. Reduce to a simmer, cover, and cook for 15 minutes. Fluff with a fork and let cool."}, {"position": 9, "body": "Remove the roasted veggies when the cauliflower edges are charred and chickpeas are slightly shrunken."}, {"position": 10, "body": "Divide the quinoa, massaged kale, and roasted mix into 4 airtight containers. Squeeze fresh lemon over everything before sealing."}],
    image_url: null,
  },
  {
    username: "jokim",
    title: "Crunchy Peanut Tofu Slaw Bowls",
    caption: "Texture is everything. If it doesn't crunch, I don't want it!",
    description: "A health-conscious bowl that focuses on the contrast between warm, seared tofu and cold, crisp cabbage. The sauce is the star here.",
    tags: ["Vegetarian", "Healthy", "Quick"],
    details: {"servings": 2, "prep_time": "25m", "cook_time": "15m", "difficulty": "Medium"},
    ingredients: ["1 block Extra-firm tofu", "1/4 cup Cornstarch", "3 tbsp Sesame oil", "2 cups Shredded cabbage", "1 Carrot (julienned)", "1/4 cup Roasted peanuts", "1/4 cup Peanut butter", "2 tbsp Soy sauce", "1 tbsp Lime juice", "1 tsp Chili oil"],
    steps: [{"position": 1, "body": "Open the tofu package and drain the liquid. Wrap the block in a clean lint-free towel and place a heavy object (like a cast-iron skillet) on top. Press for 20 minutes to extract water."}, {"position": 2, "body": "While the tofu presses, whisk together the peanut butter, soy sauce, lime juice, and chili oil in a small bowl. Add warm water 1 teaspoon at a time until the sauce is thin enough to drizzle but thick enough to coat a spoon."}, {"position": 3, "body": "Cut the pressed tofu into 3/4-inch cubes."}, {"position": 4, "body": "Place the cubes in a bowl and sprinkle with cornstarch. Toss gently until each cube is white and powdery."}, {"position": 5, "body": "Heat a large non-stick skillet over medium-high heat with the sesame oil."}, {"position": 6, "body": "Once the oil is shimmering, add the tofu cubes. Do not crowd the pan."}, {"position": 7, "body": "Let the tofu sear undisturbed for 4 minutes until a deep golden crust forms. Flip and repeat on all sides."}, {"position": 8, "body": "In two serving bowls, create a bed of shredded cabbage and julienned carrots."}, {"position": 9, "body": "Place the hot, crispy tofu directly onto the cold greens."}, {"position": 10, "body": "Drizzle the peanut sauce generously over the tofu and finish with a heavy handful of crushed peanuts and extra chili oil for a double-crunch effect."}],
    image_url: null,
  },
  {
    username: "aishamalik",
    title: "Slow-Simmered Halal Beef Stew",
    caption: "Comfort in a bowl. This is how I say 'I love you' to my family.",
    description: "A rich, deeply spiced stew using traditional halal techniques. The beef becomes buttery- soft after a long, low-temperature simmer.",
    tags: ["Halal", "Comfort Food", "Dinner"],
    details: {"servings": 6, "prep_time": "20m", "cook_time": "2h", "difficulty": "Medium"},
    ingredients: ["2 lbs Beef chuck (halal, cubed)", "3 large Potatoes", "4 Carrots", "2 Yellow onions", "4 cloves Garlic", "1 tbsp Ginger paste", "2 tbsp Tomato paste", "4 cups Beef broth", "1 tsp Cinnamon", "1 tbsp Garam masala"],
    steps: [{"position": 1, "body": "Pat the beef cubes dry with paper towels. Season them liberally with salt and black pepper on all sides."}, {"position": 2, "body": "Heat 2 tablespoons of oil in a heavy-bottomed Dutch oven over medium-high heat until it begins to smoke slightly."}, {"position": 3, "body": "Sear the beef in batches to avoid crowding. Cook for 3 minutes per side until a dark brown crust develops. Remove the beef and set aside on a plate."}, {"position": 4, "body": "Lower the heat to medium. Add the diced onions to the pot, using a wooden spoon to scrape up all the brown bits (the fond) from the bottom. Saut\u00e9 for 8 minutes until golden."}, {"position": 5, "body": "Add the garlic and ginger paste. Stir constantly for 60 seconds so the garlic doesn't burn."}, {"position": 6, "body": "Add the tomato paste and the cinnamon/garam masala. Cook for 2 minutes, stirring often, until the paste turns a dark brick red."}, {"position": 7, "body": "Pour in the beef broth and return the seared beef (and any juices from the plate) to the pot."}, {"position": 8, "body": "Bring the liquid to a boil, then immediately turn the heat down to the lowest setting."}, {"position": 9, "body": "Cover with a tight lid and simmer for"}, {"position": 1, "body": "5 hours."}, {"position": 10, "body": "After"}, {"position": 1, "body": "5 hours, add the peeled and cubed potatoes and carrots."}, {"position": 11, "body": "Replace the lid and simmer for another 30\u201345 minutes until the vegetables are tender and the beef falls apart when pressed with a fork."}, {"position": 12, "body": "Serve in deep bowls with a side of crusty bread or rice to soak up the gravy."}],
    image_url: null,
  },
  {
    username: "danielortiz",
    title: "Sauce- First Enchilada Bake",
    caption: "I cook like I\u2019m feeding a whole family even when it\u2019s just me. Sauce-first mindset .",
    description: "A massive , cheesy, saucy tray of comfort. The secret is \"frying\" the tortillas in sauce before layering to ensure they don't get gummy.",
    tags: ["Comfort Food", "Dinner", "Spicy"],
    details: {"servings": 8, "prep_time": "20m", "cook_time": "30m", "difficulty": "Easy"},
    ingredients: ["1 lb Ground beef", "2 cans Enchilada sauce", "12 Corn tortillas", "3 cups Shredded Monterey Jack", "1 can Black beans", "1 White onion", "2 tbsp Taco seasoning", "Sour cream", "Cilantro"],
    steps: [{"position": 1, "body": "Preheat your oven to 375\u00b0F (190\u00b0C)."}, {"position": 2, "body": "In a large skillet over medium heat, brown the ground beef with the diced white onion. Drain about half the fat once cooked."}, {"position": 3, "body": "Stir in the taco seasoning and the drained black beans. Add 1/2 cup of the enchilada sauce to the meat mixture to keep it moist."}, {"position": 4, "body": "In a separate wide, shallow pan, pour the rest of the enchilada sauce and warm it over low heat."}, {"position": 5, "body": "Grab a 9x13 inch baking dish. Spread a thin layer of sauce on the bottom to prevent sticking."}, {"position": 6, "body": "One by one, take a corn tortilla and dip it into the warm sauce pan, coating both sides completely."}, {"position": 7, "body": "Lay the sauce-coated tortilla in the baking dish, fill with 2 tablespoons of the meat mixture and a sprinkle of cheese, then roll it tightly."}, {"position": 8, "body": "Repeat until the dish is packed with rolls."}, {"position": 9, "body": "Pour every remaining drop of sauce over the top of the rolls. There should be no dry edges visible."}, {"position": 10, "body": "Cover the entire surface with the remaining"}, {"position": 2, "body": "5 cups of shredded cheese."}, {"position": 11, "body": "Bake for 20\u201325 minutes until the cheese is bubbling and starting to brown at the corners."}, {"position": 12, "body": "Let it sit for 10 minutes before serving\u2014this allows the sauce to thicken so the enchiladas hold their shape. Top with globs of sour cream and fresh cilantro."}],
    image_url: null,
  },
  {
    username: "keirathompson",
    title: "10-Minute Vegan Buffalo Cauliflower",
    caption: "Mostly plant-based, occasionally chaotic, always hungry.",
    description: "A fast-paced recipe for the \"always hungry\" cook. Uses the air fryer to get maximum crunch without the mess of deep frying.",
    tags: ["Vegan", "Healthy", "Quick", "Spicy"],
    details: {"servings": 2, "prep_time": "5m", "cook_time": "15m", "difficulty": "Easy"},
    ingredients: ["1 head Cauliflower", "1/2 cup Buffalo hot sauce", "1 tbsp Melted coconut oil", "1 tsp Garlic powder", "1/2 cup Flour (or Almond flour)", "1/4 cup Water", "Vegan ranch for dipping"],
    steps: [{"position": 1, "body": "Plug in your air fryer and set it to 400\u00b0F (200\u00b0C) to preheat."}, {"position": 2, "body": "Chop the cauliflower into medium-sized florets. Don't worry about being perfect\u2014varied sizes add texture."}, {"position": 3, "body": "In a large bowl, whisk together the flour, water, and garlic powder to create a thin batter. It should be the consistency of heavy cream."}, {"position": 4, "body": "Toss the cauliflower florets in the batter until they are lightly coated. Shake off any major excess."}, {"position": 5, "body": "Place the florets into the air fryer basket in a single layer. You may need to do this in two batches to ensure they aren't touching."}, {"position": 6, "body": "Air fry for 10 minutes. Halfway through (at 5 minutes), pull the basket out and give it a vigorous shake to flip the pieces."}, {"position": 7, "body": "While they fry, mix the buffalo sauce and melted coconut oil in a clean bowl."}, {"position": 8, "body": "Once the 10 minutes are up, the cauliflower should look dry and slightly golden. Transfer them into the bowl with the buffalo sauce and toss rapidly to coat."}, {"position": 9, "body": "Return the coated cauliflower to the air fryer for a final 3\u20135 minutes. This \"sets\" the sauce and makes them tacky and crispy."}, {"position": 10, "body": "Serve immediately in a bowl with a side of cold vegan ranch. Eat them while they're piping hot! Chef Username Recipe Title Caption Description Details Tags Ingredients Steps"}],
    image_url: null,
  },
  {
    username: "samirpatel",
    title: "The 'Always Mine' Masala Cauliflower",
    caption: "I tweak every recipe once and pretend it was always mine.",
    description: "A spice-heavy roasted cauliflower dish that uses a double-tempering technique. It\u2019s smoky, earthy, and bold.",
    tags: ["Vegetarian", "Healthy", "Spicy", "Dinner"],
    details: {"servings": 3, "prep_time": "10m", "cook_time": "25m", "difficulty": "Medium"},
    ingredients: ["1 large Cauliflower", "3 tbsp Avocado oil"],
    steps: [{"position": 1, "body": "5 tsp Cumin seeds; 1 tsp Turmeric ; 1 tsp Kashmiri chili powder; 1 tsp Amchur (Mango powder); Fresh Cilantro; 1 Lime"}, {"position": 1, "body": "Preheat your oven to 425\u00b0F (220\u00b0C). High heat is mandatory for the char Samir loves."}, {"position": 2, "body": "Cut the cauliflower into flat-edged steaks or large florets; flat surfaces maximize contact with the pan for better browning."}, {"position": 3, "body": "In a small glass bowl, combine the oil, turmeric , and chili powder. Whisk until the oil is a deep red/orange."}, {"position": 4, "body": "Lay the cauliflower on a sheet pan and pour the spiced oil over it. Use your hands to rub the oil into every crevice."}, {"position": 5, "body": "Roast for 20 minutes, flipping halfway through, until the edges are dark brown (almost burnt)."}, {"position": 6, "body": "The Samir Twist: While the cauliflower roasts, heat 1 tbsp of oil in a small pan. Add the cumin seeds. When they start to sizzle and pop (about 30 seconds ), remove from heat."}, {"position": 7, "body": "Remove the cauliflower from the oven and immediately pour the hot cumin oil over the hot veggies."}, {"position": 8, "body": "Sprinkle the Amchur powder over the top for a sour kick."}, {"position": 9, "body": "Garnish with a massive amount of chopped cilantro and a final squeeze of lime before serving."}],
    image_url: null,
  },
  {
    username: "samirpatel",
    title: "Triple-Spice Chickpea Kadai",
    caption: "Spice cabinet enthusiast? This one uses the whole shelf.",
    description: "A thick, dry-style chickpea curry that relies on toasted whole spices rather than a watery sauce.",
    tags: ["Vegetarian", "Healthy", "Spicy", "Dinner"],
    details: {"servings": 4, "prep_time": "15m", "cook_time": "20m", "difficulty": "Medium"},
    ingredients: ["2 cans Chickpeas", "1 Red onion", "2 Green chilies", "1 inch Ginger", "1 tbsp Coriander seeds", "1 tsp Fennel seeds", "1 tsp Black peppercorns", "1 can Diced tomatoes", "2 tsp Garam masala"],
    steps: [{"position": 1, "body": "In a dry skillet over medium heat, toast the coriander seeds, fennel seeds, and peppercorns for 2 minutes until they smell nutty."}, {"position": 2, "body": "Transfer the toasted seeds to a mortar and pestle or spice grinder and crush them into a coarse powder."}, {"position": 3, "body": "Heat oil in a large pan and saut\u00e9 finely diced red onions until they turn a deep translucent purple."}, {"position": 4, "body": "Add the ginger paste and slit green chilies. Saut\u00e9 for 2 minutes."}, {"position": 5, "body": "Add the canned tomatoes and cook them down until the oil starts to separate from the sides of the paste."}, {"position": 6, "body": "Stir in your homemade toasted spice powder and the garam masala."}, {"position": 7, "body": "Add the drained chickpeas and 1/4 cup of water."}, {"position": 8, "body": "Use the back of your spoon to mash about 10% of the chickpeas; this creates a thick \"gravy\" that clings to the rest."}, {"position": 9, "body": "Simmer for 10 minutes until the water has evaporated and the chickpeas are coated in a thick, spicy paste."}],
    image_url: null,
  },
  {
    username: "samirpatel",
    title: "Burnt Garlic & Chili Fried Rice",
    caption: "The secret is the garlic... and then adding more garlic.",
    description: "A vegetarian win that focuses on the \"tweak\" \u2014adding way more garlic than any normal recipe suggests.",
    tags: ["Vegetarian", "Quick", "Spicy"],
    details: {"servings": 2, "prep_time": "10m", "cook_time": "10m", "difficulty": "Easy"},
    ingredients: ["2 cups Day-old Basmati rice", "10 cloves Garlic", "2 tbsp Chili oil", "1 tbsp Soy sauce", "1 tsp Sugar", "1 bunch Scallions", "1 tsp Toasted sesame oil"],
    steps: [{"position": 1, "body": "Ensure your rice is cold and \"dry\" from the fridge. If it's fresh, it will get mushy."}, {"position": 2, "body": "Peel and finely mince all 10 cloves of garlic."}, {"position": 3, "body": "Heat a wok or large skillet over high heat until it smokes. Add 2 tbsp of neutral oil."}, {"position": 4, "body": "Drop the garlic into the oil. Stir constantly for about 45 seconds . You want it to turn a dark golden brown, almost \"burnt,\" but not black/bitter."}, {"position": 5, "body": "Immediately add the cold rice to the pan. Use a spatula to break up any clumps."}, {"position": 6, "body": "Pour the chili oil and soy sauce over the rice."}, {"position": 7, "body": "Toss everything on high heat for 3-4 minutes. You should hear the rice \"pop\" in the pan."}, {"position": 8, "body": "Stir in the sugar and sesame oil at the very end to balance the heat."}, {"position": 9, "body": "Garnish with sliced scallions and serve in a large bowl."}],
    image_url: null,
  },
  {
    username: "oliviabrooks",
    title: "Air Fryer 'Extreme Crunch ' Chicken",
    caption: "If it\u2019s not crispy, I don\u2019t want it.",
    description: "Olivia's signature method. The double- coating of cornstarch and a high-heat air fry creates a glass-like crunch.",
    tags: ["Comfort Food", "Quick", "Dinner"],
    details: {"servings": 2, "prep_time": "10m", "cook_time": "18m", "difficulty": "Easy"},
    ingredients: ["1 lb Chicken thighs", "1/2 cup Cornstarch", "1 tsp Garlic powder", "1 tsp Onion powder", "1/2 tsp Salt", "Spray oil", "1/4 cup Buffalo sauce"],
    steps: [{"position": 1, "body": "Cut chicken thighs into 2-inch chunks."}, {"position": 2, "body": "In a large plastic bag or bowl, mix cornstarch, garlic powder, onion powder, and salt."}, {"position": 3, "body": "Toss the chicken in the powder until every piece is fully white and heavily coated."}, {"position": 4, "body": "Preheat your air fryer to 400\u00b0F (204\u00b0C)."}, {"position": 5, "body": "Place chicken in the basket. Crucial: Do not overlap the pieces. Space = Crunch."}, {"position": 6, "body": "Spray the chicken liberally with oil spray until no white powder is visible."}, {"position": 7, "body": "Air fry for 10 minutes."}, {"position": 8, "body": "Open the basket, flip the pieces, and spray any remaining dry spots with oil."}, {"position": 9, "body": "Air fry for another 8 minutes until the chicken sounds like a \"thud\" when tapped with a fork."}, {"position": 10, "body": "Toss in a bowl with buffalo sauce and serve immediately while the crust is at its peak."}],
    image_url: null,
  },
  {
    username: "oliviabrooks",
    title: "Stovetop Crispy Smashed Potatoes",
    caption: "Air fryer + stovetop = best combo.",
    description: "A two-step process that uses the air fryer to soften and the stovetop to create a deep, buttery sear.",
    tags: ["Vegetarian", "Comfort Food", "Healthy"],
    details: {"servings": 4, "prep_time": "5m", "cook_time": "25m", "difficulty": "Medium"},
    ingredients: ["1 lb Baby potatoes", "2 tbsp Butter", "1 tbsp Olive oil", "2 cloves Garlic", "1 tsp Rosemary", "Sea salt"],
    steps: [{"position": 1, "body": "Place the whole baby potatoes in the air fryer at 400\u00b0F for 15 minutes until the skin is wrinkled and the inside is soft."}, {"position": 2, "body": "Remove the potatoes and place them on a cutting board."}, {"position": 3, "body": "Use the bottom of a heavy glass to gently \"smash\" each potato until it is about 1/2 inch thick but still in one piece."}, {"position": 4, "body": "Heat a large stainless steel or cast iron skillet over medium -high heat with the olive oil and butter."}, {"position": 5, "body": "Once the butter is foaming , place the smashed potatoes in the pan."}, {"position": 6, "body": "Press down with a spatula and sear for 4 minutes per side. Do not move them! You want a dark brown crust."}, {"position": 7, "body": "In the last 2 minutes, add the minced garlic and rosemary to the butter in the pan."}, {"position": 8, "body": "Spoon the garlic butter over the potatoes as they finish."}, {"position": 9, "body": "Season with flaky sea salt and eat immediately."}],
    image_url: null,
  },
  {
    username: "oliviabrooks",
    title: "Crispy Air-Fried Chickpea Salad",
    caption: "Crunchy toppings are a personality trait.",
    description: "This turns a boring salad into a texture powerhouse by air frying chickpeas until they are like croutons.",
    tags: ["Vegetarian", "Healthy", "Quick"],
    details: {"servings": 2, "prep_time": "5m", "cook_time": "15m", "difficulty": "Easy"},
    ingredients: ["1 can Chickpeas", "1 tsp Smoked Paprika", "1 tsp Cumin", "4 cups Arugula", "1/4 cup Feta", "1 Cucumber"],
    steps: [{"position": 1, "body": "Drain the chickpeas and dry them between two paper towels until they are 100% dry."}, {"position": 2, "body": "Toss with a tiny bit of oil and the spices."}, {"position": 3, "body": "Air fry at 390\u00b0F for 12-15 minutes, shaking the basket every 4 minutes."}, {"position": 4, "body": "They are done when they feel light and \"hollow\" when you shake the basket."}, {"position": 5, "body": "Let them cool for 2 minutes (they get crispier as they cool)."}, {"position": 6, "body": "Toss the arugula and cucumber with a simple lemon/oil dressing ."}, {"position": 7, "body": "Top the salad with the hot, crunchy chickpeas and feta cheese."}],
    image_url: null,
  },
  {
    username: "oliviabrooks",
    title: "Honey- Garlic Crispy Tofu Bites",
    caption: "The air fryer is a tofu's best friend.",
    description: "Tofu that actually tastes like it was deep-fried, but without the grease.",
    tags: ["Vegetarian", "Quick", "Dinner"],
    details: {"servings": 2, "prep_time": "15m", "cook_time": "15m", "difficulty": "Medium"},
    ingredients: ["1 block Extra-firm tofu", "2 tbsp Cornstarch", "2 tbsp Honey", "1 tbsp Soy sauce", "1 tsp Ginger"],
    steps: [{"position": 1, "body": "Press the tofu for 15 minutes to remove moisture."}, {"position": 2, "body": "Tear the tofu into \"natural\" jagged chunks rather than cubes; the jagged edges get much crispier."}, {"position": 3, "body": "Toss in cornstarch and salt."}, {"position": 4, "body": "Air fry at 400\u00b0F for 15 minutes, shaking halfway."}, {"position": 5, "body": "While frying, whisk honey, soy sauce, and ginger in a pan over medium heat until it bubbles and thickens into a syrup."}, {"position": 6, "body": "Toss the crispy tofu in the warm syrup for 30 seconds until glazed."}],
    image_url: null,
  },
  {
    username: "natewallace",
    title: "High-Protein Chicken & Pesto Pasta",
    caption: "Gym days = high protein. Rest days = pasta. I don\u2019t make the rules.",
    description: "A muscle- building meal that doesn't taste like \"diet food.\" The pesto adds the healthy fats Nate needs.",
    tags: ["Healthy", "Dinner", "Comfort Food"],
    details: {"servings": 2, "prep_time": "10m", "cook_time": "12m", "difficulty": "Easy"},
    ingredients: ["2 Chicken breasts", "2 cups Protein Pasta (Chickpea or Lentil)", "1/4 cup Pesto", "1/2 cup Greek Yogurt", "1 cup Spinach"],
    steps: [{"position": 1, "body": "Bring a large pot of salted water to a boil. Add the protein pasta and cook 1 minute less than the box instructions for \"al dente.\""}, {"position": 2, "body": "While the water boils, slice the chicken into thin strips. Season with salt and pepper."}, {"position": 3, "body": "Heat a skillet over medium -high and sear the chicken for 3-4 minutes per side until cooked through."}, {"position": 4, "body": "In a small bowl, whisk the pesto and Greek yogurt together . This creates a high-protein \"cream\" sauce without the heavy cream."}, {"position": 5, "body": "Drain the pasta, but reserve 1/4 cup of the pasta water."}, {"position": 6, "body": "Add the pasta and spinach to the chicken skillet. The residual heat will wilt the spinach in 30 seconds ."}, {"position": 7, "body": "Turn off the heat and stir in the pesto-yogurt mixture."}, {"position": 8, "body": "Add a splash of pasta water to loosen the sauce until it's perfectly glossy."}, {"position": 9, "body": "Serve immediately for 40g+ of protein per serving."}],
    image_url: null,
  },
  {
    username: "natewallace",
    title: "Rest Day Vodka Sauce Rigatoni",
    caption: "Recovery starts with carbs and a lot of cheese .",
    description: "A classic, heavy-hitting comfort meal for those much-needed rest days.",
    tags: ["Comfort Food", "Dinner"],
    details: {"servings": 4, "prep_time": "5m", "cook_time": "20m", "difficulty": "Medium"},
    ingredients: ["1 lb Rigatoni", "1 jar Marinara", "1/4 cup Heavy cream", "2 tbsp Vodka", "1/2 cup Parmesan", "Red pepper flakes"],
    steps: [{"position": 1, "body": "Boil the rigatoni in a huge pot of water. Make it \"salty like the sea.\""}, {"position": 2, "body": "In a large saucepan, pour the marinara and add the vodka and red pepper flakes."}, {"position": 3, "body": "Simmer the sauce over medium heat for 7-8 minutes. You need the alcohol to cook off so you get the flavor without the bite."}, {"position": 4, "body": "Stir in the heavy cream. The sauce should turn a beautiful sunset orange."}, {"position": 5, "body": "Once the pasta is done, transfer it directly into the sauce using a slotted spoon (don't worry about the water dripping in, it helps!)."}, {"position": 6, "body": "Stir in the parmesan cheese until it melts and the sauce clings to the ridges of the rigatoni."}, {"position": 7, "body": "Serve in a massive bowl and don't count the calories."}],
    image_url: null,
  },
  {
    username: "natewallace",
    title: "The Post-Workout Steak Bowl",
    caption: "Simple , clean, and efficient protein.",
    description: "A no-nonsense bowl for someone who wants to eat and get on with their day.",
    tags: ["Healthy", "Dinner", "Quick"],
    details: {"servings": 1, "prep_time": "5m", "cook_time": "10m", "difficulty": "Easy"},
    ingredients: ["8oz Sirloin steak", "1 bag Frozen rice", "1 cup Broccoli", "1 tbsp Soy sauce", "1 tsp Garlic salt"],
    steps: [{"position": 1, "body": "Take the steak out of the fridge 15 minutes early so it cooks evenly. Season with garlic salt."}, {"position": 2, "body": "Heat a skillet over high heat with a teaspoon of oil."}, {"position": 3, "body": "Sear the steak for 3 minutes per side (for medium -rare). Remove and let it rest for 5 minutes. CRITICAL: Do not cut it immediately or the juices will run out."}, {"position": 4, "body": "While the steak rests, microwave the frozen rice and steam the broccoli in the same microwave (usually 3 mins)."}, {"position": 5, "body": "Slice the steak against the grain into thin strips."}, {"position": 6, "body": "Build the bowl: rice on the bottom, broccoli on the side, steak on top."}, {"position": 7, "body": "Drizzle with soy sauce and eat. Chef Username Recipe Title Caption Description Details Tags Ingredients Steps"}],
    image_url: null,
  },
  {
    username: "priyashah",
    title: "The 'Lazy But Good' Butter Chickpeas",
    caption: "Indian-ish cooking with modern shortcuts. You're welcome.",
    description: "A \"makhani\" style dish that swaps labor-intensive onion bases for high-quality marinara sauce. It's a 15-minute miracle.",
    tags: ["Vegetarian", "Comfort Food", "Quick", "Healthy"],
    details: {"servings": 3, "prep_time": "5m", "cook_time": "10m", "difficulty": "Easy"},
    ingredients: ["2 cans Chickpeas", "1 cup Premium Marinara Sauce", "1/2 cup Heavy cream", "1 tbsp Butter", "1 tsp Garam masala", "1/2 tsp Turmeric", "Fresh Cilantro"],
    steps: [{"position": 1, "body": "Open the cans of chickpeas, drain them into a colander, and rinse thoroughly under cold water."}, {"position": 2, "body": "Place a large skillet over medium heat and melt the butter until it starts to foam."}, {"position": 3, "body": "Add the garam masala and turmeric to the melted butter. Stir for 30 seconds to \"bloom\" the spices\u2014this unlocks the oils and flavor."}, {"position": 4, "body": "Pour in the marinara sauce. Stir to combine with the spiced butter and bring to a gentle simmer."}, {"position": 5, "body": "Add the rinsed chickpeas to the pan. Stir until every chickpea is coated."}, {"position": 6, "body": "Lower the heat to low and pour in the heavy cream. Stir in a circular motion until the sauce turns a bright, creamy orange."}, {"position": 7, "body": "Let it simmer for 3\u20135 minutes just to let the chickpeas heat through."}, {"position": 8, "body": "Taste a chickpea; if it needs more salt, add it now."}, {"position": 9, "body": "Garnish with a handful of torn cilantro and serve with microwaveable naan or rice."}],
    image_url: null,
  },
  {
    username: "priyashah",
    title: "Short-Cut Aloo Gobi Bake",
    caption: "No standing over a stove. Just toss, roast, and eat.",
    description: "Traditionally a slow-saut\u00e9ed dish, Priya\u2019s version uses the oven to get the potatoes crispy without the constant stirring.",
    tags: ["Vegetarian", "Healthy", "Dinner"],
    details: {"servings": 4, "prep_time": "10m", "cook_time": "30m", "difficulty": "Easy"},
    ingredients: ["1 head Cauliflower", "2 large Russet potatoes", "3 tbsp Oil", "1 tsp Cumin seeds", "1 tsp Turmeric", "1 tsp Amchur powder", "1/2 tsp Cayenne"],
    steps: [{"position": 1, "body": "Preheat your oven to 425\u00b0F (220\u00b0C)."}, {"position": 2, "body": "Peel the potatoes and cut them into 1/2-inch cubes. Cut the cauliflower into small, bite-sized florets."}, {"position": 3, "body": "In a large bowl, whisk together the oil, turmeric, cayenne, and cumin seeds."}, {"position": 4, "body": "Dump the potatoes and cauliflower into the bowl. Toss vigorously until the veggies are stained bright yellow and the cumin seeds are evenly distributed."}, {"position": 5, "body": "Spread onto a large baking sheet. Do not crowd the pan; use two sheets if necessary to ensure the potatoes crisp up."}, {"position": 6, "body": "Roast for 25\u201330 minutes. At the 15-minute mark, use a spatula to toss the veggies so they brown on all sides."}, {"position": 7, "body": "Remove from the oven once the potatoes are fork-tender and the cauliflower edges are charred."}, {"position": 8, "body": "Sprinkle the Amchur (mango powder) over the hot veggies for that signature tang."}],
    image_url: null,
  },
  {
    username: "priyashah",
    title: "Cheat-Code Masala Corn",
    caption: "Street food vibes in five minutes flat.",
    description: "A snackable, spicy corn dish inspired by Indian \"Bhutta, \" but made in a pan with frozen corn.",
    tags: ["Vegetarian", "Spicy", "Quick"],
    details: {"servings": 2, "prep_time": "2m", "cook_time": "5m", "difficulty": "Easy"},
    ingredients: ["2 cups Frozen corn", "1 tbsp Butter", "1/2 tsp Chaat Masala", "1/4 tsp Chili powder", "1/2 Lime", "Salt"],
    steps: [{"position": 1, "body": "Heat a non-stick skillet over medium- high heat and add the butter."}, {"position": 2, "body": "Once the butter is melted and hot, add the frozen corn directly (no need to thaw)."}, {"position": 3, "body": "Saut\u00e9 for 3\u20134 minutes, stirring occasionally. You want some of the corn kernels to get a golden-brown sear."}, {"position": 4, "body": "Turn off the heat."}, {"position": 5, "body": "Sprinkle the Chaat Masala and chili powder over the corn."}, {"position": 6, "body": "Squeeze the lime juice over the top while the pan is still hot\u2014the juice will deglaze the pan and create a tiny bit of sauce."}, {"position": 7, "body": "Toss everything together and serve in small cups."}],
    image_url: null,
  },
  {
    username: "ethancarter",
    title: "One-Pan Sausage & Pepper Bake",
    caption: "Weeknight meals for people who hate dishes. One-pan and done.",
    description: "A rustic, hearty meal where the juices from the sausage season the peppers and onions as they roast.",
    tags: ["Dinner", "Comfort Food", "Quick"],
    details: {"servings": 4, "prep_time": "10m", "cook_time": "25m", "difficulty": "Easy"},
    ingredients: ["1 lb Italian Sausages (Links)", "3 Bell peppers (mixed colors)", "1 Red onion", "2 tbsp Olive oil", "1 tbsp Dried Oregano", "1/2 tsp Red pepper flakes"],
    steps: [{"position": 1, "body": "Preheat your oven to 400\u00b0F (200\u00b0C)."}, {"position": 2, "body": "Slice the bell peppers into 1/2-inch wide strips, discarding the seeds."}, {"position": 3, "body": "Peel the red onion and cut it into thick wedges."}, {"position": 4, "body": "Place the peppers and onions onto a large rimmed sheet pan. Drizzle with olive oil, oregano, and red pepper flakes. Toss with your hands to coat."}, {"position": 5, "body": "Arrange the sausages on top of the vegetables, spacing them out evenly."}, {"position": 6, "body": "Use a fork to prick each sausage link once or twice; this allows the fat to escape and season the vegetables below."}, {"position": 7, "body": "Roast for 20\u201325 minutes."}, {"position": 8, "body": "Halfway through, use tongs to flip the sausages and stir the peppers so they don't burn."}, {"position": 9, "body": "The dish is done when the sausages are browned and the peppers are soft and slightly charred."}, {"position": 10, "body": "Serve as is, or inside hoagie rolls if you\u2019re feeling extra hungry."}],
    image_url: null,
  },
  {
    username: "ethancarter",
    title: "Sheet Pan Lemon- Garlic Salmon",
    caption: "Clean eating without the cleanup .",
    description: "A foolproof way to cook salmon and greens together. Everything finishes at the exact same time.",
    tags: ["Healthy", "Dinner", "Quick"],
    details: {"servings": 2, "prep_time": "5m", "cook_time": "12m", "difficulty": "Easy"},
    ingredients: ["2 Salmon fillets", "1 bunch Asparagus", "1 Lemon", "2 cloves Garlic", "1 tbsp Butter", "1 tbsp Olive oil"],
    steps: [{"position": 1, "body": "Preheat oven to 400\u00b0F (200\u00b0C) and line a pan with foil."}, {"position": 2, "body": "Snap the woody ends off the asparagus and lay them on one half of the pan."}, {"position": 3, "body": "Place the salmon fillets on the other half."}, {"position": 4, "body": "Mince the garlic and mix it with melted butter and olive oil."}, {"position": 5, "body": "Drizzle the garlic-butter mixture over both the salmon and the asparagus."}, {"position": 6, "body": "Slice the lemon into thin rounds and lay them directly on top of the salmon."}, {"position": 7, "body": "Bake for 12 minutes. Check the salmon with a fork; it should flake easily in the center."}, {"position": 8, "body": "Remove from the oven and serve. Toss the foil in the trash\u2014no pan scrubbing required."}],
    image_url: null,
  },
  {
    username: "sofianguyen",
    title: "Smashed Cucumber Chili Oil Salad",
    caption: "My fridge is 70% sauces, and this uses the best ones.",
    description: "A bright, refreshing, and dangerously spicy salad. The \"smashing\" technique allows the sauce to penetrate the cucumber deeply.",
    tags: ["Healthy", "Spicy", "Quick"],
    details: {"servings": 2, "prep_time": "15m", "cook_time": "0m", "difficulty": "Easy"},
    ingredients: ["2 English Cucumbers", "2 tbsp Chili Oil (with flakes)", "1 tbsp Black Vinegar", "1 tsp Sugar", "2 cloves Garlic", "1 tsp Sesame seeds", "Salt"],
    steps: [{"position": 1, "body": "Place the cucumbers on a cutting board. Take a wide knife or a rolling pin and \"smash\" them until they split open and flatten."}, {"position": 2, "body": "Tear or cut the smashed cucumbers into bite-sized , irregular chunks."}, {"position": 3, "body": "Place the chunks in a bowl and toss with a generous pinch of salt. Let them sit for 10 minutes."}, {"position": 4, "body": "Drain the excess water that has pooled in the bottom of the bowl."}, {"position": 5, "body": "In a small jar, whisk together the chili oil, black vinegar, sugar, and grated garlic."}, {"position": 6, "body": "Pour the dressing over the cucumbers."}, {"position": 7, "body": "Toss well so the chili flakes get stuck in the jagged edges of the cucumbers."}, {"position": 8, "body": "Sprinkle with sesame seeds and serve cold."}],
    image_url: null,
  },
  {
    username: "sofianguyen",
    title: "Garlic Butter Chili Oil Noodles",
    caption: "Love bright flavors: lime, herbs, chili oils.",
    description: "A 10-minute noodle dish that is high on aromatics and heat. The butter creates a silky emulsion with the chili oil.",
    tags: ["Comfort Food", "Quick", "Spicy"],
    details: {"servings": 1, "prep_time": "2m", "cook_time": "8m", "difficulty": "Easy"},
    ingredients: ["1 portion Lo Mein or Udon noodles", "2 tbsp Butter", "2 tbsp Chili oil", "3 cloves Garlic", "1 tbsp Soy sauce", "1/2 Lime", "Fresh Cilantro"],
    steps: [{"position": 1, "body": "Boil your noodles according to the package instructions."}, {"position": 2, "body": "While they boil, finely mince the garlic."}, {"position": 3, "body": "In a small skillet or wok over medium heat, melt the butter."}, {"position": 4, "body": "Add the garlic to the butter and cook for 1 minute until fragrant but not brown."}, {"position": 5, "body": "Add the chili oil and soy sauce to the pan, stirring to combine."}, {"position": 6, "body": "Drain the noodles and immediately toss them into the skillet with the garlic butter."}, {"position": 7, "body": "Turn the heat to high and toss for 60 seconds so the sauce coats every noodle."}, {"position": 8, "body": "Remove from heat, squeeze the lime juice over the top, and garnish with a mountain of fresh cilantro."}],
    image_url: null,
  },
  {
    username: "hannahprice",
    title: "Accidentally Vegan Chocolate Mousse",
    caption: "Dessert counts as balance .",
    description: "You would never guess the secret ingredient: the liquid from a can of chickpeas (aquafaba). It\u2019s light, airy, and decadent.",
    tags: ["Vegan", "Dessert", "Gluten -Free"],
    details: {"servings": 4, "prep_time": "15m", "cook_time": "5m", "difficulty": "Medium"},
    ingredients: ["1 can Chickpeas (liquid only)", "1 cup Vegan Dark Chocolate chips", "2 tbsp Maple syrup", "1 tsp Vanilla", "Sea salt"],
    steps: [{"position": 1, "body": "Drain the liquid from the chickpea can into a large, very clean glass bowl. Set the chickpeas aside for another recipe."}, {"position": 2, "body": "Use a hand mixer or stand mixer to beat the chickpea liquid on high speed for 5\u20138 minutes. It will transform into stiff, white peaks that look like meringue ."}, {"position": 3, "body": "While the liquid is whipping, melt the chocolate chips in the microwave in 30-second intervals, stirring until smooth."}, {"position": 4, "body": "Stir the maple syrup and vanilla into the melted chocolate . Let the chocolate cool slightly (it should be warm, not hot)."}, {"position": 5, "body": "Take one scoop of the \"fluff\" and stir it into the chocolate to lighten it."}, {"position": 6, "body": "Very gently, fold the rest of the fluff into the chocolate using a spatula. Do not stir fast, or you will deflate the bubbles."}, {"position": 7, "body": "Spoon into small glasses and refrigerate for at least 2 hours."}, {"position": 8, "body": "Sprinkle with sea salt before serving."}],
    image_url: null,
  },
  {
    username: "hannahprice",
    title: "One-Bowl Vegan PB Cookies",
    caption: "Mostly vegan, sometimes just \u2018accidentally\u2019 vegan.",
    description: "A 3-ingredient base that results in a chewy, rich cookie that just happens to have no dairy or eggs.",
    tags: ["Vegan", "Dessert", "Quick"],
    details: {"servings": 12, "prep_time": "10m", "cook_time": "10m", "difficulty": "Easy"},
    ingredients: ["1 cup Creamy Peanut Butter", "3/4 cup Coconut sugar (or brown sugar)", "1/4 cup Almond milk"],
    steps: [{"position": 1, "body": "5 cups Flour; 1 tsp Baking soda"}, {"position": 1, "body": "Preheat oven to 350\u00b0F (175\u00b0C)."}, {"position": 2, "body": "In a large bowl, stir the peanut butter and sugar together until smooth."}, {"position": 3, "body": "Add the almond milk and stir until combined ."}, {"position": 4, "body": "Fold in the flour and baking soda until a thick dough forms."}, {"position": 5, "body": "Roll the dough into 1-inch balls and place them on a parchment-lined baking sheet."}, {"position": 6, "body": "Use a fork to press a \"criss-cross\" pattern into the top of each cookie."}, {"position": 7, "body": "Bake for 10 minutes exactly."}, {"position": 8, "body": "The cookies will look soft when they come out; let them cool on the pan for 10 minutes to firm up. Chef Username Recipe Title Caption Description Details Tags Ingredients Steps"}],
    image_url: null,
  },
  {
    username: "malikjohnson",
    title: "Finesse Baked Mac & Cheese",
    caption: "Comfort food with a little finesse . No box allowed.",
    description: "A soul-food staple using a custard -style base for a rich, heavy texture that stays creamy under a crusty top.",
    tags: ["Halal", "Comfort Food", "Dinner"],
    details: {"servings": 8, "prep_time": "20m", "cook_time": "35m", "difficulty": "Medium"},
    ingredients: ["1 lb Elbow macaroni", "1 lb Sharp Cheddar (shredded)", "1/2 lb Mozzarella", "1 can Evaporated milk", "2 Eggs", "1 tsp Paprika", "1/2 tsp Garlic powder", "4 tbsp Butter"],
    steps: [{"position": 1, "body": "Preheat your oven to 350\u00b0F (175\u00b0C) and grease a 9x13 inch baking dish with butter."}, {"position": 2, "body": "Bring a large pot of water to a rolling boil. Add a handful of salt."}, {"position": 3, "body": "Boil the macaroni for 2 minutes less than the package instructions. It should be firm to the bite (al dente) as it will finish cooking in the oven."}, {"position": 4, "body": "Drain the pasta and return it to the hot pot. Immediately toss with 4 tbsp of butter until melted."}, {"position": 5, "body": "In a separate bowl, whisk together the eggs, evaporated milk, paprika, and garlic powder until completely smooth."}, {"position": 6, "body": "Layer half of the buttered macaroni in the baking dish. Cover with half of the shredded cheddar and mozzarella."}, {"position": 7, "body": "Add the remaining macaroni , then pour the egg/milk mixture evenly over the entire dish."}, {"position": 8, "body": "Top with the remaining cheese, ensuring every corner is covered to prevent the pasta from drying out."}, {"position": 9, "body": "Bake for 30-35 minutes until the edges are bubbling and the top has developed a golden-brown, slightly crispy crust."}, {"position": 10, "body": "Let it rest for 10 minutes before slicing so the custard sets."}],
    image_url: null,
  },
  {
    username: "malikjohnson",
    title: "Big Flavor Halal Beef Stew",
    caption: "I'm here for big stews and even bigger flavors.",
    description: "A thick, gravy-based stew that relies on browning the meat deeply to build a complex base.",
    tags: ["Halal", "Comfort Food", "Dinner"],
    details: {"servings": 6, "prep_time": "25m", "cook_time": "2.5h", "difficulty": "Medium"},
    ingredients: ["2 lbs Beef chuck (Halal)", "4 large Carrots", "3 Potatoes", "1 Yellow onion", "3 tbsp Flour", "4 cups Beef broth", "1 tbsp Worcestershire sauce", "2 sprigs Thyme"],
    steps: [{"position": 1, "body": "Cut the beef chuck into"}, {"position": 1, "body": "5-inch chunks. Pat them dry with a paper towel; if they are wet, they will steam instead of sear."}, {"position": 2, "body": "Season the beef heavily with salt and pepper."}, {"position": 3, "body": "Heat 2 tbsp of oil in a heavy Dutch oven over high heat. Sear the beef in batches, giving each piece space. Cook for 4 minutes per side until a dark brown crust forms. Remove meat."}, {"position": 4, "body": "Reduce heat to medium. Add diced onions and cook for 10 minutes until they are soft and brown."}, {"position": 5, "body": "Stir in the flour and cook for 2 minutes, stirring constantly to create a \"roux\" with the leftover fat."}, {"position": 6, "body": "Slowly pour in the beef broth while whisking to ensure no flour lumps remain."}, {"position": 7, "body": "Return the beef to the pot. Add Worcestershire sauce and thyme."}, {"position": 8, "body": "Bring to a simmer, then cover and turn heat to low. Cook for"}, {"position": 1, "body": "5 hours."}, {"position": 9, "body": "Add peeled, chopped carrots and potatoes. Cover and cook for another 45 minutes."}, {"position": 10, "body": "The stew is ready when the beef breaks apart with the slight pressure of a spoon."}],
    image_url: null,
  },
  {
    username: "isabellarossi",
    title: "Pasta Night Vodka Sauce",
    caption: "Pasta night is a lifestyle . This is the upgrade.",
    description: "A velvety, bright orange sauce that uses vodka to unlock hidden flavors in the tomatoes.",
    tags: ["Comfort Food", "Dinner", "Vegetarian"],
    details: {"servings": 4, "prep_time": "5m", "cook_time": "20m", "difficulty": "Easy"},
    ingredients: ["1 lb Penne", "1 jar Crushed tomatoes", "2 cloves Garlic", "1/4 cup Vodka", "1/2 cup Heavy cream", "1/2 cup Parmesan", "1 tsp Red pepper flakes", "Fresh Basil"],
    steps: [{"position": 1, "body": "Set a large pot of water to boil with plenty of salt."}, {"position": 2, "body": "In a large skillet, saut\u00e9 minced garlic in olive oil over medium heat for 1 minute."}, {"position": 3, "body": "Pour in the crushed tomatoes and add red pepper flakes."}, {"position": 4, "body": "Carefully pour in the vodka. Let the sauce simmer for 7-10 minutes. You want the sharp smell of alcohol to disappear, leaving a sweet aroma."}, {"position": 5, "body": "While sauce simmers, drop your pasta into the boiling water."}, {"position": 6, "body": "Lower the skillet heat and stir in the heavy cream. The sauce will turn a creamy pink/orange."}, {"position": 7, "body": "Add 1/2 cup of parmesan cheese to the sauce and stir until melted and glossy."}, {"position": 8, "body": "Drain the pasta, reserving 1/2 cup of pasta water."}, {"position": 9, "body": "Toss the pasta into the skillet. If the sauce is too thick, add a splash of the reserved pasta water."}, {"position": 10, "body": "Tear fresh basil leaves over the top and serve immediately."}],
    image_url: null,
  },
  {
    username: "isabellarossi",
    title: "Quick Chicken Piccata",
    caption: "Italian -American classic, made in under 20 minutes.",
    description: "A bright, lemony dish with a buttery caper sauce that feels fancy but is incredibly fast.",
    tags: ["Dinner", "Quick"],
    details: {"servings": 2, "prep_time": "10m", "cook_time": "10m", "difficulty": "Medium"},
    ingredients: ["2 Chicken breasts (butterflied)", "1/2 cup Flour", "4 tbsp Butter", "1/4 cup Lemon juice", "2 tbsp Capers", "1/4 cup White wine (optional)"],
    steps: [{"position": 1, "body": "Slice your chicken breasts in half horizontally to create thin cutlets."}, {"position": 2, "body": "Place cutlets between plastic wrap and pound them with a heavy pan until they are an even 1/2 inch thickness ."}, {"position": 3, "body": "Dredge each cutlet in flour, shaking off the excess."}, {"position": 4, "body": "Heat 2 tbsp of butter and 1 tbsp of oil in a skillet over medium- high heat."}, {"position": 5, "body": "Fry chicken for 3 minutes per side until golden brown. Remove and set aside."}, {"position": 6, "body": "In the same pan, add the lemon juice, wine, and capers. Scrape the bottom of the pan to get the flavorful bits."}, {"position": 7, "body": "Let the liquid reduce by half (about 3 minutes)."}, {"position": 8, "body": "Whisk in the remaining 2 tbsp of butter to create a silky, thickened sauce."}, {"position": 9, "body": "Return the chicken to the pan for 1 minute to coat."}, {"position": 10, "body": "Garnish with fresh parsley and serve."}],
    image_url: null,
  },
  {
    username: "gracelee",
    title: "Mandatory Crunch Miso Slaw",
    caption: "Vegetarian but never boring. Texture matters . Crunch is mandatory.",
    description: "A salad built entirely around sound. No soft ingredients allowed \u2014only crisp, cold, and crunchy.",
    tags: ["Vegetarian", "Healthy", "Quick"],
    details: {"servings": 2, "prep_time": "15m", "cook_time": "0m", "difficulty": "Easy"},
    ingredients: ["1/2 head Red Cabbage", "2 Carrots", "1 Red bell pepper", "1/2 cup Edamame", "2 tbsp Miso paste", "1 tbsp Ginger", "1/4 cup Rice vinegar", "1/2 cup Crispy wonton strips"],
    steps: [{"position": 1, "body": "Finely shred the red cabbage into very thin ribbons using a sharp knife or mandoline."}, {"position": 2, "body": "Julienne the carrots and bell pepper into matchsticks of the same size."}, {"position": 3, "body": "In a large mixing bowl, whisk together the miso paste, grated ginger, and rice vinegar until it forms a smooth, thick dressing."}, {"position": 4, "body": "Add the cabbage, carrots, pepper, and edamame to the bowl."}, {"position": 5, "body": "Use tongs to toss the vegetables in the dressing for at least 60 seconds. You want the miso to get into the folds of the cabbage."}, {"position": 6, "body": "The Grace Step: Do not add the wonton strips yet!"}, {"position": 7, "body": "Let the salad sit in the fridge for 10 minutes to chill and marry flavors."}, {"position": 8, "body": "Just before serving, top the bowl with a massive, overflowing handful of crispy wonton strips."}, {"position": 9, "body": "Mix and eat immediately so the strips don't get soggy."}],
    image_url: null,
  },
  {
    username: "noahsimmons",
    title: "Roommate-Sized Sheet Pan Nachos",
    caption: "I cook for whoever\u2019s nearby. Big batches, bigger vibes.",
    description: "The ultimate \"crowd\" food. The trick is the double- layer of cheese to prevent dry chips at the bottom.",
    tags: ["Comfort Food", "Dinner"],
    details: {"servings": 6, "prep_time": "10m", "cook_time": "12m", "difficulty": "Easy"},
    ingredients: ["2 bags Tortilla chips", "1 lb Ground beef", "1 packet Taco seasoning", "4 cups Shredded Mexican blend cheese", "1 can Black beans", "2 Jalape\u00f1os", "1 jar Salsa"],
    steps: [{"position": 1, "body": "Preheat oven to 400\u00b0F (200\u00b0C)."}, {"position": 2, "body": "In a skillet, brown the ground beef. Drain the grease and stir in the taco seasoning and a splash of water."}, {"position": 3, "body": "On a massive, foil-lined baking sheet, spread out one bag of chips."}, {"position": 4, "body": "Sprinkle half of the beef, half of the beans, and 2 cups of cheese over the first layer."}, {"position": 5, "body": "Add the second bag of chips on top."}, {"position": 6, "body": "Add the remaining beef, beans, and the final 2 cups of cheese. Top with sliced jalape\u00f1os ."}, {"position": 7, "body": "Bake for 10-12 minutes. Watch closely! You want the cheese melted and the chip edges just starting to brown."}, {"position": 8, "body": "Remove from oven and immediately dollop salsa and sour cream all over the tray."}, {"position": 9, "body": "Place in the center of the table and let everyone dig in directly from the pan."}],
    image_url: null,
  },
  {
    username: "zarakhan",
    title: "Halal Turkey Meatball Prep",
    caption: "Halal meals + meal prep. I keep it flavorful and realistic.",
    description: "A lean, high-protein meal prep that uses cumin and garlic to keep the turkey from being bland.",
    tags: ["Halal", "Healthy", "Quick"],
    details: {"servings": 4, "prep_time": "15m", "cook_time": "20m", "difficulty": "Easy"},
    ingredients: ["1 lb Ground turkey (Halal)", "1/2 cup Breadcrumbs", "1 Egg", "1 tsp Cumin", "1 tsp Garlic powder", "1/2 tsp Onion powder", "2 cups Cooked Rice", "1 head Broccoli"],
    steps: [{"position": 1, "body": "Preheat oven to 400\u00b0F (200\u00b0C). Line a tray with parchment."}, {"position": 2, "body": "In a large bowl, combine ground turkey, breadcrumbs, egg, cumin, garlic powder, and onion powder."}, {"position": 3, "body": "Use your hands to mix until just combined . Do not overmix or the meatballs will be tough."}, {"position": 4, "body": "Roll the mixture into balls about the size of a golf ball (should make about 12-16)."}, {"position": 5, "body": "Place on the tray and bake for 18-20 minutes. Cut one open to ensure it's no longer pink."}, {"position": 6, "body": "While meatballs bake, steam the broccoli in a pot with a little water for 5 minutes."}, {"position": 7, "body": "Portion out 4 meal prep containers with 1/2 cup rice and a pile of broccoli."}, {"position": 8, "body": "Add 3-4 meatballs to each container."}, {"position": 9, "body": "Drizzle with a little soy sauce or hot sauce before sealing for the week. Chef Username Recipe Title Caption Description Details Tags Ingredients Steps"}],
    image_url: null,
  },
  {
    username: "malikjohnson",
    title: "Finesse Baked Mac & Cheese",
    caption: "Comfort food with a little finesse . No box allowed.",
    description: "A soul-food staple using a custard -style base for a rich, heavy texture that stays creamy under a crusty top.",
    tags: ["Halal", "Comfort Food", "Dinner"],
    details: {"servings": 8, "prep_time": "20m", "cook_time": "35m", "difficulty": "Medium"},
    ingredients: ["1 lb Elbow macaroni", "1 lb Sharp Cheddar (shredded)", "1/2 lb Mozzarella", "1 can Evaporated milk", "2 Eggs", "1 tsp Paprika", "1/2 tsp Garlic powder", "4 tbsp Butter"],
    steps: [{"position": 1, "body": "Preheat your oven to 350\u00b0F (175\u00b0C) and grease a 9x13 inch baking dish with butter."}, {"position": 2, "body": "Bring a large pot of water to a rolling boil. Add a handful of salt."}, {"position": 3, "body": "Boil the macaroni for 2 minutes less than the package instructions. It should be firm to the bite (al dente) as it will finish cooking in the oven."}, {"position": 4, "body": "Drain the pasta and return it to the hot pot. Immediately toss with 4 tbsp of butter until melted."}, {"position": 5, "body": "In a separate bowl, whisk together the eggs, evaporated milk, paprika, and garlic powder until completely smooth."}, {"position": 6, "body": "Layer half of the buttered macaroni in the baking dish. Cover with half of the shredded cheddar and mozzarella."}, {"position": 7, "body": "Add the remaining macaroni , then pour the egg/milk mixture evenly over the entire dish."}, {"position": 8, "body": "Top with the remaining cheese, ensuring every corner is covered to prevent the pasta from drying out."}, {"position": 9, "body": "Bake for 30-35 minutes until the edges are bubbling and the top has developed a golden-brown, slightly crispy crust."}, {"position": 10, "body": "Let it rest for 10 minutes before slicing so the custard sets."}],
    image_url: null,
  },
  {
    username: "malikjohnson",
    title: "Big Flavor Halal Beef Stew",
    caption: "I'm here for big stews and even bigger flavors.",
    description: "A thick, gravy-based stew that relies on browning the meat deeply to build a complex base.",
    tags: ["Halal", "Comfort Food", "Dinner"],
    details: {"servings": 6, "prep_time": "25m", "cook_time": "2.5h", "difficulty": "Medium"},
    ingredients: ["2 lbs Beef chuck (Halal)", "4 large Carrots", "3 Potatoes", "1 Yellow onion", "3 tbsp Flour", "4 cups Beef broth", "1 tbsp Worcestershire sauce", "2 sprigs Thyme"],
    steps: [{"position": 1, "body": "Cut the beef chuck into"}, {"position": 1, "body": "5-inch chunks. Pat them dry with a paper towel; if they are wet, they will steam instead of sear."}, {"position": 2, "body": "Season the beef heavily with salt and pepper."}, {"position": 3, "body": "Heat 2 tbsp of oil in a heavy Dutch oven over high heat. Sear the beef in batches, giving each piece space. Cook for 4 minutes per side until a dark brown crust forms. Remove meat."}, {"position": 4, "body": "Reduce heat to medium. Add diced onions and cook for 10 minutes until they are soft and brown."}, {"position": 5, "body": "Stir in the flour and cook for 2 minutes, stirring constantly to create a \"roux\" with the leftover fat."}, {"position": 6, "body": "Slowly pour in the beef broth while whisking to ensure no flour lumps remain."}, {"position": 7, "body": "Return the beef to the pot. Add Worcestershire sauce and thyme."}, {"position": 8, "body": "Bring to a simmer, then cover and turn heat to low. Cook for"}, {"position": 1, "body": "5 hours."}, {"position": 9, "body": "Add peeled, chopped carrots and potatoes. Cover and cook for another 45 minutes."}, {"position": 10, "body": "The stew is ready when the beef breaks apart with the slight pressure of a spoon."}],
    image_url: null,
  },
  {
    username: "isabellarossi",
    title: "Pasta Night Vodka Sauce",
    caption: "Pasta night is a lifestyle . This is the upgrade.",
    description: "A velvety, bright orange sauce that uses vodka to unlock hidden flavors in the tomatoes.",
    tags: ["Comfort Food", "Dinner", "Vegetarian"],
    details: {"servings": 4, "prep_time": "5m", "cook_time": "20m", "difficulty": "Easy"},
    ingredients: ["1 lb Penne", "1 jar Crushed tomatoes", "2 cloves Garlic", "1/4 cup Vodka", "1/2 cup Heavy cream", "1/2 cup Parmesan", "1 tsp Red pepper flakes", "Fresh Basil"],
    steps: [{"position": 1, "body": "Set a large pot of water to boil with plenty of salt."}, {"position": 2, "body": "In a large skillet, saut\u00e9 minced garlic in olive oil over medium heat for 1 minute."}, {"position": 3, "body": "Pour in the crushed tomatoes and add red pepper flakes."}, {"position": 4, "body": "Carefully pour in the vodka. Let the sauce simmer for 7-10 minutes. You want the sharp smell of alcohol to disappear, leaving a sweet aroma."}, {"position": 5, "body": "While sauce simmers, drop your pasta into the boiling water."}, {"position": 6, "body": "Lower the skillet heat and stir in the heavy cream. The sauce will turn a creamy pink/orange."}, {"position": 7, "body": "Add 1/2 cup of parmesan cheese to the sauce and stir until melted and glossy."}, {"position": 8, "body": "Drain the pasta, reserving 1/2 cup of pasta water."}, {"position": 9, "body": "Toss the pasta into the skillet. If the sauce is too thick, add a splash of the reserved pasta water."}, {"position": 10, "body": "Tear fresh basil leaves over the top and serve immediately."}],
    image_url: null,
  },
  {
    username: "isabellarossi",
    title: "Quick Chicken Piccata",
    caption: "Italian -American classic, made in under 20 minutes.",
    description: "A bright, lemony dish with a buttery caper sauce that feels fancy but is incredibly fast.",
    tags: ["Dinner", "Quick"],
    details: {"servings": 2, "prep_time": "10m", "cook_time": "10m", "difficulty": "Medium"},
    ingredients: ["2 Chicken breasts (butterflied)", "1/2 cup Flour", "4 tbsp Butter", "1/4 cup Lemon juice", "2 tbsp Capers", "1/4 cup White wine (optional)"],
    steps: [{"position": 1, "body": "Slice your chicken breasts in half horizontally to create thin cutlets."}, {"position": 2, "body": "Place cutlets between plastic wrap and pound them with a heavy pan until they are an even 1/2 inch thickness ."}, {"position": 3, "body": "Dredge each cutlet in flour, shaking off the excess."}, {"position": 4, "body": "Heat 2 tbsp of butter and 1 tbsp of oil in a skillet over medium- high heat."}, {"position": 5, "body": "Fry chicken for 3 minutes per side until golden brown. Remove and set aside."}, {"position": 6, "body": "In the same pan, add the lemon juice, wine, and capers. Scrape the bottom of the pan to get the flavorful bits."}, {"position": 7, "body": "Let the liquid reduce by half (about 3 minutes)."}, {"position": 8, "body": "Whisk in the remaining 2 tbsp of butter to create a silky, thickened sauce."}, {"position": 9, "body": "Return the chicken to the pan for 1 minute to coat."}, {"position": 10, "body": "Garnish with fresh parsley and serve."}],
    image_url: null,
  },
  {
    username: "gracelee",
    title: "Mandatory Crunch Miso Slaw",
    caption: "Vegetarian but never boring. Texture matters . Crunch is mandatory.",
    description: "A salad built entirely around sound. No soft ingredients allowed \u2014only crisp, cold, and crunchy.",
    tags: ["Vegetarian", "Healthy", "Quick"],
    details: {"servings": 2, "prep_time": "15m", "cook_time": "0m", "difficulty": "Easy"},
    ingredients: ["1/2 head Red Cabbage", "2 Carrots", "1 Red bell pepper", "1/2 cup Edamame", "2 tbsp Miso paste", "1 tbsp Ginger", "1/4 cup Rice vinegar", "1/2 cup Crispy wonton strips"],
    steps: [{"position": 1, "body": "Finely shred the red cabbage into very thin ribbons using a sharp knife or mandoline."}, {"position": 2, "body": "Julienne the carrots and bell pepper into matchsticks of the same size."}, {"position": 3, "body": "In a large mixing bowl, whisk together the miso paste, grated ginger, and rice vinegar until it forms a smooth, thick dressing."}, {"position": 4, "body": "Add the cabbage, carrots, pepper, and edamame to the bowl."}, {"position": 5, "body": "Use tongs to toss the vegetables in the dressing for at least 60 seconds. You want the miso to get into the folds of the cabbage."}, {"position": 6, "body": "The Grace Step: Do not add the wonton strips yet!"}, {"position": 7, "body": "Let the salad sit in the fridge for 10 minutes to chill and marry flavors."}, {"position": 8, "body": "Just before serving, top the bowl with a massive, overflowing handful of crispy wonton strips."}, {"position": 9, "body": "Mix and eat immediately so the strips don't get soggy."}],
    image_url: null,
  },
  {
    username: "noahsimmons",
    title: "Roommate-Sized Sheet Pan Nachos",
    caption: "I cook for whoever\u2019s nearby. Big batches, bigger vibes.",
    description: "The ultimate \"crowd\" food. The trick is the double- layer of cheese to prevent dry chips at the bottom.",
    tags: ["Comfort Food", "Dinner"],
    details: {"servings": 6, "prep_time": "10m", "cook_time": "12m", "difficulty": "Easy"},
    ingredients: ["2 bags Tortilla chips", "1 lb Ground beef", "1 packet Taco seasoning", "4 cups Shredded Mexican blend cheese", "1 can Black beans", "2 Jalape\u00f1os", "1 jar Salsa"],
    steps: [{"position": 1, "body": "Preheat oven to 400\u00b0F (200\u00b0C)."}, {"position": 2, "body": "In a skillet, brown the ground beef. Drain the grease and stir in the taco seasoning and a splash of water."}, {"position": 3, "body": "On a massive, foil-lined baking sheet, spread out one bag of chips."}, {"position": 4, "body": "Sprinkle half of the beef, half of the beans, and 2 cups of cheese over the first layer."}, {"position": 5, "body": "Add the second bag of chips on top."}, {"position": 6, "body": "Add the remaining beef, beans, and the final 2 cups of cheese. Top with sliced jalape\u00f1os ."}, {"position": 7, "body": "Bake for 10-12 minutes. Watch closely! You want the cheese melted and the chip edges just starting to brown."}, {"position": 8, "body": "Remove from oven and immediately dollop salsa and sour cream all over the tray."}, {"position": 9, "body": "Place in the center of the table and let everyone dig in directly from the pan."}],
    image_url: null,
  },
  {
    username: "zarakhan",
    title: "Halal Turkey Meatball Prep",
    caption: "Halal meals + meal prep. I keep it flavorful and realistic.",
    description: "A lean, high-protein meal prep that uses cumin and garlic to keep the turkey from being bland.",
    tags: ["Halal", "Healthy", "Quick"],
    details: {"servings": 4, "prep_time": "15m", "cook_time": "20m", "difficulty": "Easy"},
    ingredients: ["1 lb Ground turkey (Halal)", "1/2 cup Breadcrumbs", "1 Egg", "1 tsp Cumin", "1 tsp Garlic powder", "1/2 tsp Onion powder", "2 cups Cooked Rice", "1 head Broccoli"],
    steps: [{"position": 1, "body": "Preheat oven to 400\u00b0F (200\u00b0C). Line a tray with parchment."}, {"position": 2, "body": "In a large bowl, combine ground turkey, breadcrumbs, egg, cumin, garlic powder, and onion powder."}, {"position": 3, "body": "Use your hands to mix until just combined . Do not overmix or the meatballs will be tough."}, {"position": 4, "body": "Roll the mixture into balls about the size of a golf ball (should make about 12-16)."}, {"position": 5, "body": "Place on the tray and bake for 18-20 minutes. Cut one open to ensure it's no longer pink."}, {"position": 6, "body": "While meatballs bake, steam the broccoli in a pot with a little water for 5 minutes."}, {"position": 7, "body": "Portion out 4 meal prep containers with 1/2 cup rice and a pile of broccoli."}, {"position": 8, "body": "Add 3-4 meatballs to each container."}, {"position": 9, "body": "Drizzle with a little soy sauce or hot sauce before sealing for the week. Chef Username Recipe Title Caption Description Details Tags Ingredients Steps"}],
    image_url: null,
  },
  {
    username: "ananyadeshmukh",
    title: "Clean -Slate Shrimp & Veggie Stir-Fry",
    caption: "I like clean ingredients but I\u2019m not a robot. Tacos and stir-fry forever.",
    description: "A vibrantly fresh, low-sodium stir-fry that focuses on the natural snap of the vegetables and high-quality seafood.",
    tags: ["Healthy", "Quick", "Dinner"],
    details: {"servings": 2, "prep_time": "15m", "cook_time": "8m", "difficulty": "Easy"},
    ingredients: ["1 lb Large shrimp (peeled/deveined)", "2 cups Broccoli florets", "1 Red bell pepper", "2 tbsp Ginger (minced)", "3 tbsp Coconut aminos (or soy sauce)", "1 tsp Sesame oil", "2 cups Cauliflower rice"],
    steps: [{"position": 1, "body": "Pat the shrimp completely dry with paper towels; if they are wet, they will steam instead of getting a golden sear."}, {"position": 2, "body": "Heat a large wok or stainless steel skillet over high heat until a drop of water flicked onto it dances and evaporates instantly."}, {"position": 3, "body": "Add 1 tbsp of neutral oil and the shrimp. Sear for 90 seconds per side until opaque and pink. Remove shrimp and set aside on a plate."}, {"position": 4, "body": "Add another splash of oil and toss in the broccoli and sliced bell peppers. Stir-fry vigorously for 3 minutes until the broccoli is bright green but still has a firm \"snap.\""}, {"position": 5, "body": "Push the veggies to the sides of the pan and drop the minced ginger into the center. Cook for 30 seconds until the aroma hits you."}, {"position": 6, "body": "Pour in the coconut aminos and sesame oil. The liquid should bubble and reduce slightly."}, {"position": 7, "body": "Return the shrimp to the pan and toss everything together for 60 seconds to glaze."}, {"position": 8, "body": "Serve over steamed cauliflower rice for a totally \"clean\" but filling meal."}],
    image_url: null,
  },
  {
    username: "averychen",
    title: "SF Market Green Goddess Soup",
    caption: "SF meal prep + farmers market haul energy. Simple, seasonal, fast.",
    description: "A vibrant, silk-textured soup that captures the essence of a California spring. No cream required\u2014the potato provides all the body.",
    tags: ["Vegan", "Healthy", "Quick"],
    details: {"servings": 4, "prep_time": "10m", "cook_time": "20m", "difficulty": "Easy"},
    ingredients: ["2 bunches Spinach", "2 large Leeks (white parts only)", "2 Yukon Gold potatoes", "4 cups Vegetable broth", "1 Lemon", "1/4 cup Fresh chives", "2 tbsp Olive oil"],
    steps: [{"position": 1, "body": "Cut the leeks in half lengthwise and rinse thoroughly under running water to remove any trapped sand. Thinly slice the white and light green parts."}, {"position": 2, "body": "Peel the potatoes and cut them into very small 1/2-inch cubes (smaller cubes cook faster for a \"quick\" meal)."}, {"position": 3, "body": "In a large pot, heat olive oil over medium heat. Add the leeks and a pinch of salt. Saut\u00e9 for 5-7 minutes until soft and buttery, but not browned."}, {"position": 4, "body": "Stir in the potato cubes and pour in the vegetable broth."}, {"position": 5, "body": "Bring to a boil, then reduce heat to a simmer . Cover and cook for 12-15 minutes until the potatoes are completely tender when pressed with a spoon."}, {"position": 6, "body": "Turn off the heat. Dump the spinach and chives into the hot liquid. Stir for 30 seconds until the spinach wilts and turns a brilliant emerald green."}, {"position": 7, "body": "Using an immersion blender (or transferring in batches to a stand blender ), blend the soup on the highest setting until it is completely smooth and frothy."}, {"position": 8, "body": "Stir in the juice of half a lemon to brighten the flavor."}, {"position": 9, "body": "Serve hot or cold with a drizzle of high-quality olive oil on top."}],
    image_url: null,
  },
  {
    username: "leomartinez",
    title: "Miso- Butter Fusion Spaghetti",
    caption: "Fusion experiments that somehow work. I\u2019m chasing the perfect bite.",
    description: "A Japanese-Italian hybrid that creates an umami \"bomb. \" The miso adds a fermented depth that mimics a very aged parmesan.",
    tags: ["Comfort Food", "Dinner", "Vegetarian"],
    details: {"servings": 2, "prep_time": "5m", "cook_time": "12m", "difficulty": "Medium"},
    ingredients: ["8 oz Spaghetti", "2 tbsp White miso paste", "4 tbsp Unsalted butter (softened)", "1 tbsp Soy sauce", "1 sheet Nori (shredded)", "1 tsp Togarashi (spice blend)", "1/4 cup Pasta water"],
    steps: [{"position": 1, "body": "Bring a pot of water to a boil. Use less water than usual; you want the water to be extra starchy for the sauce. Add a pinch of salt (less than usual, as miso is salty)."}, {"position": 2, "body": "Boil spaghetti until 1 minute before \"al dente.\""}, {"position": 3, "body": "While pasta cooks, place the softened butter and miso paste in a small bowl. Use a fork to mash them together until they form a smooth , uniform beige paste."}, {"position": 4, "body": "Just before draining, dip a measuring cup into the pasta water and save at least 1/2 cup."}, {"position": 5, "body": "Drain the pasta and return it to the pot over low heat."}, {"position": 6, "body": "Add the miso-butter mixture and the soy sauce."}, {"position": 7, "body": "Slowly pour in the reserved pasta water, 1 tablespoon at a time, while tossing the noodles vigorously with tongs."}, {"position": 8, "body": "Keep tossing until the butter and water emulsify into a creamy , glossy sauce that clings to every strand."}, {"position": 9, "body": "Plate the pasta and top with shredded nori strips and a generous dusting of Togarashi for heat and color."}],
    image_url: null,
  },
  {
    username: "ishanivyas",
    title: "Minimalist Ginger-Tofu Broth",
    caption: "Minimalist cooking. Big on broth, noodles, and clean flavors.",
    description: "A meditative, healing bowl of soup. This recipe focuses on the clarity of the broth and the delicate texture of silken tofu.",
    tags: ["Vegetarian", "Healthy", "Quick"],
    details: {"servings": 2, "prep_time": "10m", "cook_time": "15m", "difficulty": "Easy"},
    ingredients: ["1 block Silken tofu", "4 cups High-quality veggie broth", "3-inch piece of Ginger", "2 cloves Garlic", "2 heads Bok choy", "1 bunch Scallions", "1 tsp Sesame oil"],
    steps: [{"position": 1, "body": "Peel the ginger using the edge of a spoon. Slice it into very thin coins, then stack them and slice into matchsticks."}, {"position": 2, "body": "Smash the garlic cloves but leave them whole (this flavors the broth without making it cloudy with bits)."}, {"position": 3, "body": "Pour the vegetable broth into a pot and add the ginger and smashed garlic. Bring to a simmer over medium heat for 10 minutes to infuse."}, {"position": 4, "body": "While the broth simmers, cut the silken tofu into 1-inch cubes. Handle it very gently \u2014it\u2019s fragile!"}, {"position": 5, "body": "Trim the ends of the bok choy and slice the leaves into wide ribbons ."}, {"position": 6, "body": "Use a slotted spoon to remove the garlic cloves from the broth (leave the ginger for a spicy bite)."}, {"position": 7, "body": "Add the bok choy and simmer for 2 minutes until the stems are translucent."}, {"position": 8, "body": "Carefully slide the tofu cubes into the broth. Do not stir vigorously, or the tofu will break. Let it heat through for 2 minutes."}, {"position": 9, "body": "Ladle into bowls and finish with a drop of sesame oil and a handful of finely sliced scallions."}],
    image_url: null,
  },
  {
    username: "morganblake",
    title: "High- Protein Buffalo 'Greek' Bowl",
    caption: "High-protein meals that don\u2019t taste like cardboard. Sauces save lives.",
    description: "A fitness- focused bowl that uses a clever Greek yogurt hack to make a creamy , spicy sauce without the fat of traditional buffalo dip.",
    tags: ["Healthy", "Quick", "Spicy"],
    details: {"servings": 1, "prep_time": "10m", "cook_time": "12m", "difficulty": "Easy"},
    ingredients: ["8 oz Chicken breast", "1/2 cup Non-fat Greek yogurt", "3 tbsp Buffalo hot sauce", "1/2 tsp Garlic powder", "1 cup Cooked quinoa", "2 stalks Celery (chopped)", "1/4 Red onion (diced)"],
    steps: [{"position": 1, "body": "Slice the chicken breast into small, bite-sized cubes. Season with garlic powder , salt, and pepper."}, {"position": 2, "body": "Spray a skillet with oil and heat over medium-high. Add chicken and cook for 6-8 minutes, stirring occasionally, until golden and cooked through ."}, {"position": 3, "body": "While the chicken cooks, make the \"Life-Saving Sauce\" : In a small bowl, whisk the Greek yogurt and buffalo sauce until it turns a uniform bright orange."}, {"position": 4, "body": "In a large bowl, lay down a base of warm, cooked quinoa."}, {"position": 5, "body": "Add the cooked chicken on one side and the chopped raw celery and red onion on the other. The celery is crucial for the \"crunch \" Morgan loves."}, {"position": 6, "body": "Pour the buffalo- yogurt sauce over the chicken while it's still hot."}, {"position": 7, "body": "Toss everything together so the sauce coats the quinoa and the veggies. The heat of the chicken will thin the yogurt slightly into a perfect dressing. Chef Username Recipe Title Caption Description Details Tags Ingredients Steps nadiael- amin Harissa-Spiced Chickpea Mash \"I\u2019ll make you love chickpeas. Bold, spicy, and halal-friendly.\" A protein-packed, Mediterranean-style mash that works as a dip or a main. The harissa provides a slow-building heat. Servings: 2; Prep Time: 10m; Cook Time: 10m; Difficulty: Easy Halal, Healthy, Spicy, Vegetarian 2 cans Chickpeas; 2 tbsp Harissa paste; 1/4 cup Tahini; 1 Lemon; 2 cloves Garlic; 1 tsp Cumin; Fresh Parsley; Olive oil"}, {"position": 1, "body": "Drain and rinse the chickpeas, but reserve 2 tablespoons of the canning liquid (aquafaba)."}, {"position": 2, "body": "Place a skillet over medium heat and add 1 tbsp of olive oil. Saut\u00e9 the minced garlic and cumin for 1 minute until fragrant."}, {"position": 3, "body": "Add the chickpeas to the pan and cook for 5 minutes, shaking the pan until they are warmed through and some skins begin to pop."}, {"position": 4, "body": "Use a potato masher or the back of a large fork to roughly mash about half of the chickpeas directly in the pan."}, {"position": 5, "body": "Stir in the harissa paste and the reserved chickpea liquid. This creates a thick, spicy \"sauce\" that binds the mash together ."}, {"position": 6, "body": "Remove from heat and stir in the tahini and the juice of half a lemon."}, {"position": 7, "body": "The consistency should be chunky and spreadable. If it's too thick, add a teaspoon of warm water."}, {"position": 8, "body": "Transfer to a bowl, drizzle with more olive oil, and top with a mountain of chopped parsley."}],
    image_url: null,
  },
  {
    username: "julesharper",
    title: "LA Street- Style Carne Asada Tacos",
    caption: "LA food obsession: street tacos, bowls, and anything with hot sauce.",
    description: "A tribute to the taco trucks of East LA. The key is a very hot pan and a simple, acidic marinade to tenderize the beef.",
    tags: ["Dinner", "Spicy", "Comfort Food"],
    details: {"servings": 3, "prep_time": "20m", "cook_time": "10m", "difficulty": "Medium"},
    ingredients: ["1 lb Flank steak", "2 Limes", "1/4 cup Orange juice", "2 cloves Garlic", "1/2 bunch Cilantro", "1 White onion", "12 Small corn tortillas", "Hot Sauce"],
    steps: [{"position": 1, "body": "Slice the flank steak into very thin strips against the grain."}, {"position": 2, "body": "In a bowl, combine the lime juice, orange juice, minced garlic, and chopped cilantro. Toss the steak in this mixture and let it marinate for at least 15 minutes (while you prep the toppings )."}, {"position": 3, "body": "Finely dice the white onion and chop the remaining cilantro. Mix them together in a small bowl to create a classic street taco garnish."}, {"position": 4, "body": "Heat a heavy cast-iron skillet or griddle over high heat until it is screaming hot."}, {"position": 5, "body": "Add 1 tbsp of oil. Remove the steak from the marinade, shaking off excess liquid, and drop it into the pan."}, {"position": 6, "body": "Sear for 2-3 minutes without moving it to get a charred, \"street-style\" crust. Toss and cook for 2 more minutes."}, {"position": 7, "body": "Remove the meat and let it rest."}, {"position": 8, "body": "Wipe the pan and quickly warm the corn tortillas for 30 seconds per side until they are pliable and slightly charred."}, {"position": 9, "body": "Double up the tortillas (two per taco), pile on the meat, add the onion-cilantro mix, and douse in your favorite LA-style hot sauce."}],
    image_url: null,
  },
  {
    username: "arjunrao",
    title: "Fresh Mango & Black Bean LA Bowl",
    caption: "Plant-forward LA-style. Fresh, colorful , and actually filling.",
    description: "A bright, high-fiber vegan bowl that hits the sweet-salty-spicy trifecta common in Southern California fusion.",
    tags: ["Vegan", "Healthy", "Gluten- Free"],
    details: {"servings": 2, "prep_time": "15m", "cook_time": "15m", "difficulty": "Easy"},
    ingredients: ["1 ripe Mango", "1 can Black beans", "1 cup Quinoa", "1 Avocado", "1 cup Shredded purple cabbage", "1 Lime", "1 tsp Tajin seasoning", "1 tbsp Agave"],
    steps: [{"position": 1, "body": "Rinse the quinoa under cold water and place in a pot with 2 cups of water. Bring to a boil, then cover and simmer on low for 15 minutes until fluffy."}, {"position": 2, "body": "While the quinoa cooks, peel the mango and cut the flesh into 1/2-inch cubes."}, {"position": 3, "body": "Drain and rinse the black beans."}, {"position": 4, "body": "In a small bowl, whisk together the lime juice, agave, and a pinch of salt to create a bright dressing ."}, {"position": 5, "body": "In two large bowls, create a base of warm quinoa."}, {"position": 6, "body": "Arrange the black beans, shredded cabbage, and mango cubes in sections on top of the quinoa."}, {"position": 7, "body": "Slice the avocado and place half in each bowl."}, {"position": 8, "body": "Pour the lime-agave dressing over the entire bowl."}, {"position": 9, "body": "The LA Finish: Dust the mango and avocado sections heavily with Tajin seasoning for a spicy, limey kick that ties the fruit and beans together ."}],
    image_url: null,
  },
  {
    username: "arjunrao",
    title: "Miso- Roasted Sweet Potato Tacos",
    caption: "Colorful, filling, and plant-forward.",
    description: "This recipe uses miso to add deep savory notes to roasted sweet potatoes, topped with a zesty vegan slaw.",
    tags: ["Vegan", "Healthy", "Dinner"],
    details: {"servings": 2, "prep_time": "10m", "cook_time": "25m", "difficulty": "Easy"},
    ingredients: ["2 large Sweet potatoes", "1 tbsp White miso", "2 tbsp Maple syrup", "1 tbsp Soy sauce", "6 Flour tortillas", "1 cup Slaw mix", "1 Lime"],
    steps: [{"position": 1, "body": "Preheat your oven to 400\u00b0F (200\u00b0C)."}, {"position": 2, "body": "Peel the sweet potatoes and cut them into small, even cubes (about 1/2 inch)."}, {"position": 3, "body": "In a large bowl, whisk together the miso paste, maple syrup, and soy sauce until smooth."}, {"position": 4, "body": "Toss the sweet potato cubes in the miso mixture until they are completely glazed."}, {"position": 5, "body": "Spread onto a parchment-lined baking sheet. Roast for 20-25 minutes, tossing once halfway through, until the edges are caramelized and soft."}, {"position": 6, "body": "While potatoes roast, toss your slaw mix with fresh lime juice and a pinch of salt."}, {"position": 7, "body": "Warm the tortillas in a dry pan or over a gas flame."}, {"position": 8, "body": "Fill the tortillas with the sticky miso sweet potatoes and top with the limey slaw for a perfect balance of sweet, salty, and sour."}],
    image_url: null,
  },
  {
    username: "julesharper",
    title: "Spicy 'Dirty' Breakfast Burrito",
    caption: "Street -food energy to start your day.",
    description: "A heavy-duty burrito inspired by LA's morning food truck scene, featuring crispy potatoes and spicy eggs.",
    tags: ["Breakfast", "Comfort Food", "Spicy"],
    details: {"servings": 1, "prep_time": "10m", "cook_time": "15m", "difficulty": "Medium"},
    ingredients: ["2 Eggs", "1 cup Frozen tater tots", "1 large Flour tortilla", "1/4 cup Shredded cheddar", "2 tbsp Pickled jalape\u00f1os", "2 tbsp Salsa roja"],
    steps: [{"position": 1, "body": "Air fry or pan-fry the tater tots for 12-15 minutes until they are extremely crispy. Once done, use a fork to lightly smash them."}, {"position": 2, "body": "In a small bowl, whisk the eggs with a teaspoon of your favorite hot sauce and a pinch of salt."}, {"position": 3, "body": "Scramble the eggs in a buttered pan over medium -low heat. Keep them slightly \"soft\"\u2014they will finish cooking inside the burrito."}, {"position": 4, "body": "Lay the flour tortilla flat and sprinkle the cheese in the center."}, {"position": 5, "body": "Place the hot scrambled eggs over the cheese to help it melt."}, {"position": 6, "body": "Pile the smashed crispy tater tots on top of the eggs."}, {"position": 7, "body": "Add the pickled jalape\u00f1os and salsa roja."}, {"position": 8, "body": "Fold the sides of the tortilla in and roll it up tightly."}, {"position": 9, "body": "The Pro Move: Place the rolled burrito back in the skillet for 1 minute per side to toast the outside of the tortilla and \"seal\" the seam."}],
    image_url: null,
  },
];
